# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='common',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x06\x63ommon\"t\n\x0eGENERAL_NOTICE\x12\r\n\x02id\x18\x01 \x01(\r:\x01\x30\x12\x0f\n\x04type\x18\x02 \x01(\x05:\x01\x30\x12\x16\n\x0b\x62usiness_id\x18\x03 \x01(\r:\x01\x30\x12\x18\n\tbeen_read\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x10\n\x06notice\x18\x05 \x01(\t:\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERAL_NOTICE = _descriptor.Descriptor(
  name='GENERAL_NOTICE',
  full_name='common.GENERAL_NOTICE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.GENERAL_NOTICE.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.GENERAL_NOTICE.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='business_id', full_name='common.GENERAL_NOTICE.business_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='been_read', full_name='common.GENERAL_NOTICE.been_read', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notice', full_name='common.GENERAL_NOTICE.notice', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['GENERAL_NOTICE'] = _GENERAL_NOTICE

GENERAL_NOTICE = _reflection.GeneratedProtocolMessageType('GENERAL_NOTICE', (_message.Message,), dict(
  DESCRIPTOR = _GENERAL_NOTICE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.GENERAL_NOTICE)
  ))
_sym_db.RegisterMessage(GENERAL_NOTICE)


# @@protoc_insertion_point(module_scope)
