# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='login',
  serialized_pb=_b('\n\x0blogin.proto\x12\x05login\"O\n\tREQ_LOGIN\x12\x13\n\tdevice_id\x18\x01 \x01(\t:\x00\x12\x16\n\x0c\x64\x65vice_brand\x18\x02 \x01(\t:\x00\x12\x15\n\nchannel_id\x18\x03 \x01(\x05:\x01\x30\"\xa3\x02\n\tRSP_LOGIN\x12\x0e\n\x04name\x18\x01 \x01(\t:\x00\x12\x0f\n\x04gems\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05\x63oins\x18\x03 \x01(\x05:\x01\x30\x12\x16\n\x0bserver_time\x18\x04 \x01(\x07:\x01\x30\x12\x18\n\rping_interval\x18\x05 \x01(\r:\x01\x30\x12\x10\n\x05level\x18\x06 \x01(\x05:\x01\x30\x12\x0e\n\x04icon\x18\x07 \x01(\t:\x00\x12\x1b\n\x10play_total_count\x18\x08 \x01(\x05:\x01\x30\x12\x19\n\x0eplay_win_count\x18\t \x01(\x05:\x01\x30\x12\x0e\n\x03sex\x18\n \x01(\x05:\x01\x30\x12\x14\n\troomcards\x18\x0b \x01(\x05:\x01\x30\x12\x11\n\x06result\x18\x0c \x01(\x05:\x01\x30\x12\x1e\n\x0f\x63\x61n_change_name\x18\r \x01(\x08:\x05\x66\x61lse\"6\n\nNTF_LOGOUT\x12\x11\n\x06reason\x18\x01 \x01(\x05:\x01\x30\x12\x15\n\x0b\x64\x65scription\x18\x02 \x01(\t:\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQ_LOGIN = _descriptor.Descriptor(
  name='REQ_LOGIN',
  full_name='login.REQ_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='login.REQ_LOGIN.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_brand', full_name='login.REQ_LOGIN.device_brand', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='login.REQ_LOGIN.channel_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=101,
)


_RSP_LOGIN = _descriptor.Descriptor(
  name='RSP_LOGIN',
  full_name='login.RSP_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='login.RSP_LOGIN.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gems', full_name='login.RSP_LOGIN.gems', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coins', full_name='login.RSP_LOGIN.coins', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='login.RSP_LOGIN.server_time', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping_interval', full_name='login.RSP_LOGIN.ping_interval', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='login.RSP_LOGIN.level', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='icon', full_name='login.RSP_LOGIN.icon', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='play_total_count', full_name='login.RSP_LOGIN.play_total_count', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='play_win_count', full_name='login.RSP_LOGIN.play_win_count', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='login.RSP_LOGIN.sex', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomcards', full_name='login.RSP_LOGIN.roomcards', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='login.RSP_LOGIN.result', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_change_name', full_name='login.RSP_LOGIN.can_change_name', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=395,
)


_NTF_LOGOUT = _descriptor.Descriptor(
  name='NTF_LOGOUT',
  full_name='login.NTF_LOGOUT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='login.NTF_LOGOUT.reason', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='login.NTF_LOGOUT.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=451,
)

DESCRIPTOR.message_types_by_name['REQ_LOGIN'] = _REQ_LOGIN
DESCRIPTOR.message_types_by_name['RSP_LOGIN'] = _RSP_LOGIN
DESCRIPTOR.message_types_by_name['NTF_LOGOUT'] = _NTF_LOGOUT

REQ_LOGIN = _reflection.GeneratedProtocolMessageType('REQ_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _REQ_LOGIN,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.REQ_LOGIN)
  ))
_sym_db.RegisterMessage(REQ_LOGIN)

RSP_LOGIN = _reflection.GeneratedProtocolMessageType('RSP_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _RSP_LOGIN,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.RSP_LOGIN)
  ))
_sym_db.RegisterMessage(RSP_LOGIN)

NTF_LOGOUT = _reflection.GeneratedProtocolMessageType('NTF_LOGOUT', (_message.Message,), dict(
  DESCRIPTOR = _NTF_LOGOUT,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.NTF_LOGOUT)
  ))
_sym_db.RegisterMessage(NTF_LOGOUT)


# @@protoc_insertion_point(module_scope)
