return {
  [1] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "2_man",
    ["key"] = 2,
    ["process"] = "男声打出单牌2",
  },
  [2] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "2zhangbaojing_man",
    ["key"] = -1,
    ["process"] = "男声玩家还剩2张报警",
  },
  [3] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "3_man",
    ["key"] = 3,
    ["process"] = "男声打出单牌3",
  },
  [4] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "4_man",
    ["key"] = 4,
    ["process"] = "男声打出单牌4",
  },
  [5] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "5_man",
    ["key"] = 5,
    ["process"] = "男声打出单牌5",
  },
  [6] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "6_man",
    ["key"] = 6,
    ["process"] = "男声打出单牌6",
  },
  [7] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "7_man",
    ["key"] = 7,
    ["process"] = "男声打出单牌7",
  },
  [8] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "8_man",
    ["key"] = 8,
    ["process"] = "男声打出单牌8",
  },
  [9] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "9_man",
    ["key"] = 9,
    ["process"] = "男声打出单牌9",
  },
  [10] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "10_man",
    ["key"] = 10,
    ["process"] = "男声打出单牌10",
  },
  [11] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "a_man",
    ["key"] = 1,
    ["process"] = "男声打出单牌a",
  },
  [12] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "bujiao_man",
    ["key"] = -1,
    ["process"] = "男声不叫地主",
  },
  [14] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "buqiang_man",
    ["key"] = -1,
    ["process"] = "男声不抢地主",
  },
  [15] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "buyao_man",
    ["key"] = -1,
    ["process"] = "男声选择过牌",
  },
  [16] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "dani_man",
    ["key"] = -1,
    ["process"] = "男声打出的牌压过上家（和管上随机播放）",
  },
  [17] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "dawang_man",
    ["key"] = 15,
    ["process"] = "男声打出单牌大王",
  },
  [18] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui2_man",
    ["key"] = 2,
    ["process"] = "男声打出对2",
  },
  [19] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui3_man",
    ["key"] = 3,
    ["process"] = "男声打出对3",
  },
  [20] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui4_man",
    ["key"] = 4,
    ["process"] = "男声打出对4",
  },
  [21] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui5_man",
    ["key"] = 5,
    ["process"] = "男声打出对5",
  },
  [22] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui6_man",
    ["key"] = 6,
    ["process"] = "男声打出对6",
  },
  [23] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui7_man",
    ["key"] = 7,
    ["process"] = "男声打出对7",
  },
  [24] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui8_man",
    ["key"] = 8,
    ["process"] = "男声打出对8",
  },
  [25] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui9_man",
    ["key"] = 9,
    ["process"] = "男声打出对9",
  },
  [26] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "dui10_man",
    ["key"] = 10,
    ["process"] = "男声打出对10",
  },
  [27] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "duiA_man",
    ["key"] = 1,
    ["process"] = "男声打出对A",
  },
  [28] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "duij_man",
    ["key"] = 11,
    ["process"] = "男声打出对J",
  },
  [29] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "duik_man",
    ["key"] = 13,
    ["process"] = "男声打出对k",
  },
  [30] = {
    ["sex"] = 1,
    ["type"] = 4,
    ["audio_name"] = "duiq_man",
    ["key"] = 12,
    ["process"] = "男声打出对q",
  },
  [31] = {
    ["sex"] = 1,
    ["type"] = 9,
    ["audio_name"] = "feiji_man",
    ["key"] = -1,
    ["process"] = "男声打出飞机",
  },
  [128] = {
    ["sex"] = 1,
    ["type"] = 10,
    ["audio_name"] = "feiji_man",
    ["key"] = -1,
    ["process"] = "男声打出飞机带翅膀",
  },
  [32] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "guanshang_man",
    ["key"] = -1,
    ["process"] = "男声打出的牌压过上家（和大你循环播放）",
  },
  [33] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "guo_man",
    ["key"] = -1,
    ["process"] = "男声不要上家打出的牌",
  },
  [34] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "j_man",
    ["key"] = 11,
    ["process"] = "男声打出单牌J",
  },
  [35] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "jiaodizhu_man",
    ["key"] = -1,
    ["process"] = "男声叫地主",
  },
  [36] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "k_man",
    ["key"] = 13,
    ["process"] = "男声打出单牌K",
  },
  [37] = {
    ["sex"] = 1,
    ["type"] = 8,
    ["audio_name"] = "liandui_man",
    ["key"] = -1,
    ["process"] = "男声打出连对",
  },
  [38] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "pass_man",
    ["key"] = -1,
    ["process"] = "男声选择不要",
  },
  [39] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "q_man",
    ["key"] = 12,
    ["process"] = "男声打出单牌q",
  },
  [40] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "qiangdizhu_man",
    ["key"] = -1,
    ["process"] = "男声抢地主",
  },
  [41] = {
    ["sex"] = 1,
    ["type"] = 6,
    ["audio_name"] = "sandaiyi_man",
    ["key"] = -1,
    ["process"] = "男声打出三带一",
  },
  [42] = {
    ["sex"] = 1,
    ["type"] = 13,
    ["audio_name"] = "sandaiyidui_man",
    ["key"] = -1,
    ["process"] = "男声打出三带一对",
  },
  [43] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangA_man",
    ["key"] = 1,
    ["process"] = "男声打出3张A",
  },
  [44] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangba_man",
    ["key"] = 8,
    ["process"] = "男声打出3张8",
  },
  [45] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhanger_man",
    ["key"] = 2,
    ["process"] = "男声打出3张2",
  },
  [46] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangj_man",
    ["key"] = 11,
    ["process"] = "男声打出3张j",
  },
  [47] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangjiu_man",
    ["key"] = 9,
    ["process"] = "男声打出3张9",
  },
  [48] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangK_man",
    ["key"] = 13,
    ["process"] = "男声打出3张K",
  },
  [49] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangliu_man",
    ["key"] = 6,
    ["process"] = "男声打出3张6",
  },
  [50] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangQ_man",
    ["key"] = 12,
    ["process"] = "男声打出3张Q",
  },
  [51] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangqi_man",
    ["key"] = 7,
    ["process"] = "男声打出3张7",
  },
  [52] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangsan_man",
    ["key"] = 3,
    ["process"] = "男声打出3张3",
  },
  [53] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangshi_man",
    ["key"] = 10,
    ["process"] = "男声打出3张10",
  },
  [54] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangsi_man",
    ["key"] = 4,
    ["process"] = "男声打出3张4",
  },
  [55] = {
    ["sex"] = 1,
    ["type"] = 5,
    ["audio_name"] = "sanzhangwu_man",
    ["key"] = 5,
    ["process"] = "男声打出3张5",
  },
  [56] = {
    ["sex"] = 1,
    ["type"] = 7,
    ["audio_name"] = "shunzi_man",
    ["key"] = -1,
    ["process"] = "男声打出顺子",
  },
  [57] = {
    ["sex"] = 1,
    ["type"] = 10,
    ["audio_name"] = "sidaier_man",
    ["key"] = -1,
    ["process"] = "男声打出4带2",
  },
  [58] = {
    ["sex"] = 1,
    ["type"] = 14,
    ["audio_name"] = "sidailiangdui_man",
    ["key"] = -1,
    ["process"] = "男声打出4带两对",
  },
  [59] = {
    ["sex"] = 1,
    ["type"] = 1,
    ["audio_name"] = "wangzha_man",
    ["key"] = -1,
    ["process"] = "男声打出王炸",
  },
  [60] = {
    ["sex"] = 1,
    ["type"] = 3,
    ["audio_name"] = "xiaowang_man",
    ["key"] = 14,
    ["process"] = "男声打出小王",
  },
  [61] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "yaobuqi_man",
    ["key"] = -1,
    ["process"] = "男声不要上家打出的牌，和另外一个过牌循环播放",
  },
  [62] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "yasi_man",
    ["key"] = -1,
    ["process"] = "男声压了上家的顺子，三带一等牌型",
  },
  [63] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "yizhangbaojing_man",
    ["key"] = -1,
    ["process"] = "男声一张报警",
  },
  [64] = {
    ["sex"] = 1,
    ["type"] = 2,
    ["audio_name"] = "zhadan_man",
    ["key"] = -1,
    ["process"] = "男声打出炸弹",
  },
  [65] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "2_woman",
    ["key"] = 2,
    ["process"] = "女声打出单牌2",
  },
  [66] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "2zhangbaojing_woman",
    ["key"] = -1,
    ["process"] = "女声玩家还剩2张报警",
  },
  [67] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "3_woman",
    ["key"] = 3,
    ["process"] = "女声打出单牌3",
  },
  [68] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "4_woman",
    ["key"] = 4,
    ["process"] = "女声打出单牌4",
  },
  [69] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "5_woman",
    ["key"] = 5,
    ["process"] = "女声打出单牌5",
  },
  [70] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "6_woman",
    ["key"] = 6,
    ["process"] = "女声打出单牌6",
  },
  [71] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "7_woman",
    ["key"] = 7,
    ["process"] = "女声打出单牌7",
  },
  [72] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "8_woman",
    ["key"] = 8,
    ["process"] = "女声打出单牌8",
  },
  [73] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "9_woman",
    ["key"] = 9,
    ["process"] = "女声打出单牌9",
  },
  [74] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "10_woman",
    ["key"] = 10,
    ["process"] = "女声打出单牌10",
  },
  [75] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "a_woman",
    ["key"] = 1,
    ["process"] = "女声打出单牌a",
  },
  [76] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "bujiao_woman",
    ["key"] = -1,
    ["process"] = "女声不叫地主",
  },
  [77] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "buqiang_woman",
    ["key"] = -1,
    ["process"] = "女声不抢地主",
  },
  [78] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "buyao_woman",
    ["key"] = -1,
    ["process"] = "女声选择过牌",
  },
  [79] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "dani_woman",
    ["key"] = -1,
    ["process"] = "女声打出的牌压过上家（和管上随机播放）",
  },
  [80] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "dawang_woman",
    ["key"] = 15,
    ["process"] = "女声打出单牌大王",
  },
  [81] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui2_woman",
    ["key"] = 2,
    ["process"] = "女声打出对2",
  },
  [82] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui3_woman",
    ["key"] = 3,
    ["process"] = "女声打出对3",
  },
  [83] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui4_woman",
    ["key"] = 4,
    ["process"] = "女声打出对4",
  },
  [84] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui5_woman",
    ["key"] = 5,
    ["process"] = "女声打出对5",
  },
  [85] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui6_woman",
    ["key"] = 6,
    ["process"] = "女声打出对6",
  },
  [86] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui7_woman",
    ["key"] = 7,
    ["process"] = "女声打出对7",
  },
  [87] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui8_woman",
    ["key"] = 8,
    ["process"] = "女声打出对8",
  },
  [88] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui9_woman",
    ["key"] = 9,
    ["process"] = "女声打出对9",
  },
  [89] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "dui10_woman",
    ["key"] = 10,
    ["process"] = "女声打出对10",
  },
  [90] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "duiA_woman",
    ["key"] = 1,
    ["process"] = "女声打出对A",
  },
  [91] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "duij_woman",
    ["key"] = 11,
    ["process"] = "女声打出对J",
  },
  [92] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "duik_woman",
    ["key"] = 13,
    ["process"] = "女声打出对k",
  },
  [93] = {
    ["sex"] = 2,
    ["type"] = 4,
    ["audio_name"] = "duiq_woman",
    ["key"] = 12,
    ["process"] = "女声打出对q",
  },
  [94] = {
    ["sex"] = 2,
    ["type"] = 9,
    ["audio_name"] = "feiji_woman",
    ["key"] = -1,
    ["process"] = "女声打出飞机",
  },
  [129] = {
    ["sex"] = 2,
    ["type"] = 10,
    ["audio_name"] = "feiji_woman",
    ["key"] = -1,
    ["process"] = "女声打出飞机带翅膀",
  },
  [95] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "guanshang_woman",
    ["key"] = -1,
    ["process"] = "女声打出的牌压过上家（和大你随机播放）",
  },
  [96] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "guo_woman",
    ["key"] = -1,
    ["process"] = "女声不要上家打出的牌",
  },
  [97] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "j_woman",
    ["key"] = 11,
    ["process"] = "女声打出单牌J",
  },
  [98] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "jiaodizhu_woman",
    ["key"] = -1,
    ["process"] = "女声叫地主",
  },
  [99] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "k_woman",
    ["key"] = 13,
    ["process"] = "女声打出单牌K",
  },
  [100] = {
    ["sex"] = 2,
    ["type"] = 8,
    ["audio_name"] = "liandui_woman",
    ["key"] = -1,
    ["process"] = "女声打出连对",
  },
  [101] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "pass_woman",
    ["key"] = -1,
    ["process"] = "女声选择不要",
  },
  [102] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "q_woman",
    ["key"] = 12,
    ["process"] = "女声打出单牌q",
  },
  [103] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "qiangdizhu_woman",
    ["key"] = -1,
    ["process"] = "女声抢地主",
  },
  [104] = {
    ["sex"] = 2,
    ["type"] = 6,
    ["audio_name"] = "sandaiyi_woman",
    ["key"] = -1,
    ["process"] = "女声打出三带一",
  },
  [105] = {
    ["sex"] = 2,
    ["type"] = 13,
    ["audio_name"] = "sandaiyidui_woman",
    ["key"] = -1,
    ["process"] = "女声打出三带一对",
  },
  [106] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangA_woman",
    ["key"] = 1,
    ["process"] = "女声打出3张A",
  },
  [107] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangba_woman",
    ["key"] = 8,
    ["process"] = "女声打出3张8",
  },
  [108] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhanger_woman",
    ["key"] = 2,
    ["process"] = "女声打出3张2",
  },
  [109] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangj_woman",
    ["key"] = 11,
    ["process"] = "女声打出3张j",
  },
  [110] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangjiu_woman",
    ["key"] = 9,
    ["process"] = "女声打出3张9",
  },
  [111] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangK_woman",
    ["key"] = 13,
    ["process"] = "女声打出3张K",
  },
  [112] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangliu_woman",
    ["key"] = 6,
    ["process"] = "女声打出3张6",
  },
  [113] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangQ_woman",
    ["key"] = 12,
    ["process"] = "女声打出3张Q",
  },
  [114] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangqi_woman",
    ["key"] = 7,
    ["process"] = "女声打出3张7",
  },
  [115] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangsan_woman",
    ["key"] = 3,
    ["process"] = "女声打出3张3",
  },
  [116] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangshi_woman",
    ["key"] = 10,
    ["process"] = "女声打出3张10",
  },
  [117] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangsi_woman",
    ["key"] = 4,
    ["process"] = "女声打出3张4",
  },
  [118] = {
    ["sex"] = 2,
    ["type"] = 5,
    ["audio_name"] = "sanzhangwu_woman",
    ["key"] = 5,
    ["process"] = "女声打出3张5",
  },
  [119] = {
    ["sex"] = 2,
    ["type"] = 7,
    ["audio_name"] = "shunzi_woman",
    ["key"] = -1,
    ["process"] = "女声打出顺子",
  },
  [120] = {
    ["sex"] = 2,
    ["type"] = 10,
    ["audio_name"] = "sidaier_woman",
    ["key"] = -1,
    ["process"] = "女声打出4带2",
  },
  [121] = {
    ["sex"] = 2,
    ["type"] = 14,
    ["audio_name"] = "sidailiangdui_woman",
    ["key"] = -1,
    ["process"] = "女声打出4带两对",
  },
  [122] = {
    ["sex"] = 2,
    ["type"] = 1,
    ["audio_name"] = "wangzha_woman",
    ["key"] = -1,
    ["process"] = "女声打出王炸",
  },
  [123] = {
    ["sex"] = 2,
    ["type"] = 3,
    ["audio_name"] = "xiaowang_woman",
    ["key"] = 14,
    ["process"] = "女声打出小王",
  },
  [124] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "yaobuqi_woman",
    ["key"] = -1,
    ["process"] = "女声不要上家打出的牌，和另外一个过牌随机播放",
  },
  [125] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "yasi_woman",
    ["key"] = -1,
    ["process"] = "女声压了上家的顺子，三带一等牌型",
  },
  [126] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "yizhangbaojing_woman",
    ["key"] = -1,
    ["process"] = "女声一张报警",
  },
  [127] = {
    ["sex"] = 2,
    ["type"] = 2,
    ["audio_name"] = "zhadan_woman",
    ["key"] = -1,
    ["process"] = "女声打出炸弹",
  },
  [130] = {
    ["sex"] = -1,
    ["type"] = -1,
    ["audio_name"] = "button",
    ["key"] = -1,
    ["process"] = "点击界面上所有按钮发出的声音",
  },
  [131] = {
    ["sex"] = -1,
    ["type"] = -1,
    ["audio_name"] = "backgroundmusic",
    ["key"] = -1,
    ["process"] = "进入房间后播放的背景音乐",
  },
  [132] = {
    ["sex"] = -1,
    ["type"] = -1,
    ["audio_name"] = "fapai",
    ["key"] = -1,
    ["process"] = "发牌的时候播放的动画",
  },
  [133] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "1fen_man",
    ["key"] = -1,
    ["process"] = "男声叫1分",
  },
  [134] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "2fen_man",
    ["key"] = -1,
    ["process"] = "男声叫2分",
  },
  [135] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "3fen_man",
    ["key"] = -1,
    ["process"] = "男声叫3分",
  },
  [136] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "1fen_woman",
    ["key"] = -1,
    ["process"] = "女声叫1分",
  },
  [137] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "2fen_woman",
    ["key"] = -1,
    ["process"] = "女声叫2分",
  },
  [138] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "3fen_woman",
    ["key"] = -1,
    ["process"] = "女声叫3分",
  },
  [139] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "jiabei_man",
    ["key"] = -1,
    ["process"] = "男声加倍",
  },
  [140] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "jiabei_woman",
    ["key"] = -1,
    ["process"] = "女声加倍",
  },
  [141] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "bujiabei_man",
    ["key"] = -1,
    ["process"] = "男声不加倍",
  },
  [142] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "bujiabei_woman",
    ["key"] = -1,
    ["process"] = "女声不加倍",
  },
  [143] = {
    ["sex"] = 1,
    ["type"] = -1,
    ["audio_name"] = "mingpai_man",
    ["key"] = -1,
    ["process"] = "男声明牌",
  },
  [144] = {
    ["sex"] = 2,
    ["type"] = -1,
    ["audio_name"] = "mingpai_woman",
    ["key"] = -1,
    ["process"] = "女声明牌",
  },
  [145] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "1tiao_man",
    ["key"] = 31,
    ["process"] = "男声打出1条",
  },
  [146] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "1tiao_woman",
    ["key"] = 31,
    ["process"] = "女声打出1条",
  },
  [147] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "2tiao_man",
    ["key"] = 32,
    ["process"] = "男声打出2条",
  },
  [148] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "2tiao_woman",
    ["key"] = 32,
    ["process"] = "女声打出2条",
  },
  [149] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "3tiao_man",
    ["key"] = 33,
    ["process"] = "男声打出3条",
  },
  [150] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "3tiao_woman",
    ["key"] = 33,
    ["process"] = "女声打出3条",
  },
  [151] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "4tiao_man",
    ["key"] = 34,
    ["process"] = "男声打出4条",
  },
  [152] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "4tiao_woman",
    ["key"] = 34,
    ["process"] = "女声打出4条",
  },
  [153] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "5tiao_man",
    ["key"] = 35,
    ["process"] = "男声打出5条",
  },
  [154] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "5tiao_woman",
    ["key"] = 35,
    ["process"] = "女声打出5条",
  },
  [155] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "6tiao_man",
    ["key"] = 36,
    ["process"] = "男声打出6条",
  },
  [156] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "6tiao_woman",
    ["key"] = 36,
    ["process"] = "女声打出6条",
  },
  [157] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "7tiao_man",
    ["key"] = 37,
    ["process"] = "男声打出7条",
  },
  [158] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "7tiao_woman",
    ["key"] = 37,
    ["process"] = "女声打出7条",
  },
  [159] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "8tiao_man",
    ["key"] = 38,
    ["process"] = "男声打出8条",
  },
  [160] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "8tiao_woman",
    ["key"] = 38,
    ["process"] = "女声打出8条",
  },
  [161] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "9tiao_man",
    ["key"] = 39,
    ["process"] = "男声打出9条",
  },
  [162] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "9tiao_woman",
    ["key"] = 39,
    ["process"] = "女声打出9条",
  },
  [163] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "1tong_man",
    ["key"] = 21,
    ["process"] = "男声打出1筒",
  },
  [164] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "1tong_woman",
    ["key"] = 21,
    ["process"] = "女声打出1筒",
  },
  [165] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "2tong_man",
    ["key"] = 22,
    ["process"] = "男声打出2筒",
  },
  [166] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "2tong_woman",
    ["key"] = 22,
    ["process"] = "女声打出2筒",
  },
  [167] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "3tong_man",
    ["key"] = 23,
    ["process"] = "男声打出3筒",
  },
  [168] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "3tong_woman",
    ["key"] = 23,
    ["process"] = "女声打出3筒",
  },
  [169] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "4tong_man",
    ["key"] = 24,
    ["process"] = "男声打出4筒",
  },
  [170] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "4tong_woman",
    ["key"] = 24,
    ["process"] = "女声打出4筒",
  },
  [171] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "5tong_man",
    ["key"] = 25,
    ["process"] = "男声打出5筒",
  },
  [172] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "5tong_woman",
    ["key"] = 25,
    ["process"] = "女声打出5筒",
  },
  [173] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "6tong_man",
    ["key"] = 26,
    ["process"] = "男声打出6筒",
  },
  [174] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "6tong_woman",
    ["key"] = 26,
    ["process"] = "女声打出6筒",
  },
  [175] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "7tong_man",
    ["key"] = 27,
    ["process"] = "男声打出7筒",
  },
  [176] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "7tong_woman",
    ["key"] = 27,
    ["process"] = "女声打出7筒",
  },
  [177] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "8tong_man",
    ["key"] = 28,
    ["process"] = "男声打出8筒",
  },
  [178] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "8tong_woman",
    ["key"] = 28,
    ["process"] = "女声打出8筒",
  },
  [179] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "9tong_man",
    ["key"] = 29,
    ["process"] = "男声打出9筒",
  },
  [180] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "9tong_woman",
    ["key"] = 29,
    ["process"] = "女声打出9筒",
  },
  [181] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "1wan_man",
    ["key"] = 11,
    ["process"] = "男声打出1万",
  },
  [182] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "1wan_woman",
    ["key"] = 11,
    ["process"] = "女声打出1万",
  },
  [183] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "2wan_man",
    ["key"] = 12,
    ["process"] = "男声打出2万",
  },
  [184] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "2wan_woman",
    ["key"] = 12,
    ["process"] = "女声打出2万",
  },
  [185] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "3wan_man",
    ["key"] = 13,
    ["process"] = "男声打出3万",
  },
  [186] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "3wan_woman",
    ["key"] = 13,
    ["process"] = "女声打出3万",
  },
  [187] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "4wan_man",
    ["key"] = 14,
    ["process"] = "男声打出4万",
  },
  [188] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "4wan_woman",
    ["key"] = 14,
    ["process"] = "女声打出4万",
  },
  [189] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "5wan_man",
    ["key"] = 15,
    ["process"] = "男声打出5万",
  },
  [190] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "5wan_woman",
    ["key"] = 15,
    ["process"] = "女声打出5万",
  },
  [191] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "6wan_man",
    ["key"] = 16,
    ["process"] = "男声打出6万",
  },
  [192] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "6wan_woman",
    ["key"] = 16,
    ["process"] = "女声打出6万",
  },
  [193] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "7wan_man",
    ["key"] = 17,
    ["process"] = "男声打出7万",
  },
  [194] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "7wan_woman",
    ["key"] = 17,
    ["process"] = "女声打出7万",
  },
  [195] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "8wan_man",
    ["key"] = 18,
    ["process"] = "男声打出8万",
  },
  [196] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "8wan_woman",
    ["key"] = 18,
    ["process"] = "女声打出8万",
  },
  [197] = {
    ["sex"] = 1,
    ["type"] = 0,
    ["audio_name"] = "9wan_man",
    ["key"] = 19,
    ["process"] = "男声打出9万",
  },
  [198] = {
    ["sex"] = 2,
    ["type"] = 0,
    ["audio_name"] = "9wan_woman",
    ["key"] = 19,
    ["process"] = "女声打出9万",
  },
}